include: _default_template.yaml
task: streamingbench_real_time_visual_understanding
dataset_name: real_time_visual_understanding
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: real_time_visual_understanding
    post_prompt: "Answer with the option's letter from the given choices directly."