include: _default_template.yaml
task: mlvu_mc_count
dataset_name: 4_count
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: 4_count
    post_prompt: "Answer with the option's letter from the given choices directly."