include: _default_template.yaml
task: mlvu_mc_order
dataset_name: 5_order
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: 5_order
    post_prompt: "Answer with the option's letter from the given choices directly."